### ISSUE TITLE
"A Prayer for Glampers" 

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#1]
Add comma after 'campsite': "Matthew said when we pulled up to our campsite, it was like that scene in Contact when Jodie Foster is in her space-time machine, looking at the swirling universe, and she starts crying and says it’s so beautiful that they should’ve sent a poet instead (I mean, sure, or probably an astronaut)."

**Comment by nevanscott** [comment]
I think this is fixed. Can you confirm and close out this ticket?

**Comment by rebeccarubenstein** [comment]
Confirmed.
