### ISSUE TITLE
About Page: alter copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#100]
We need to alter the copy at the bottom of the page. Instead of:

"We are currently closed for writing submissions. Please check back, or sign up for our newsletter to be notified once we’ve opened shop again."

Can it say:

"We're open for submissions! Please [go here](http://midnightbreakfast.com/submissions) for more info."

**Comment by nevanscott** [comment]
Knock yourself out:

https://github.com/midnightbreakfast/web/blob/submissions/_src/pages/about.md

(I'd prefer links to not be words like "go here" or "click here".)

**Comment by rebeccarubenstein** [comment]
Thanks for making my life easier!
