### ISSUE TITLE
Small Plates: Wendy C. Ortiz excerpt

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#105]
I've set up the excerpt, though there are two things I'm unsure of:
1. How to format the "overtitle" and "title" within the editor (I tried to mirror what you did with Shane Jones's excerpt, but it seemed to fuck up the coding).
2. How to add the book cover image. I'll drop it below, so you know where to find it.

Here's the link to the excerpt itself: https://github.com/midnightbreakfast/web/blob/smalls/_src/smalls/_posts/2014-07-25-ortiz-excavation.md

Let me know if everything looks okay. I still need to add an Editor's Note.

Book cover:

![wendyfrontcover](https://cloud.githubusercontent.com/assets/4043562/3640166/ac52cea8-1098-11e4-8abe-36a221aaabb7.jpg)

**Comment by nevanscott** [comment]
Hey, I just pushed a change to the code that should address both of these things.
