### ISSUE TITLE
Articles for Issue 2

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#107]
These should all go in here:

https://github.com/midnightbreakfast/web/tree/magazine/_src/magazine/_posts/issue002

I put an example here:

https://github.com/midnightbreakfast/web/blob/magazine/_src/magazine/_posts/issue002/2014-07-28-sample.md

Make sure that the sample gets removed as well.

**Note:** The word "sample" in the filename should be replaced with whatever you want to be the slug in the URL.

See here for how this is set up in Issue 1:

https://github.com/midnightbreakfast/web/tree/magazine/_src/magazine/_posts/issue001

Don't worry about the illustrations, just the writing. :)

**Comment by rebeccarubenstein** [comment]
Actually, scratch that last comment (in case you already read it). I'll handle setting these up, and Taylor and I will just take the reins on proofreading, like last time.

**Comment by nevanscott** [comment]
Ok, sounds good. If you ever want to alert Taylor to something on here, you can just @-mention him.

**Comment by rebeccarubenstein** [comment]
@nevanscott So...things are going smoothly. But I'm noticing none of the formatting is carrying over. Is there a way to do some awesome dev super power thing where you can automatically bold every instance of a certain word? Or italicize a handful of things? Or do I just need to do this all manually? (This is pretty much my nightmare, and is especially awful for our interview with Edan, which has a LOT of formatting.)

**Comment by nevanscott** [comment]
Mostly I've been doing it by hand. If for the interview you need me to put in the bold for the names, I have a relatively quicker way to do it myself: basically by doing find and replace.

**Comment by rebeccarubenstein** [comment]
The following articles have been proofread/formatted and just need changes pushed, but are good to go text-wise:
1. "F"
2. "In Conversation with Edan Lepucki"
3. "A Barcelona Tale"

@ftpavlik When you've had a chance to format/proofread your pieces and they're good to go, can you comment here with a similar message?

**Comment by ftpavlik** [comment]
I'll be proofreading/formatting my pieces tonight.

On Fri, Jul 25, 2014 at 9:36 PM, rebeccarubenstein <notifications@github.com

**Comment by ftpavlik** [comment]
Okay, my three pieces have also been formatted and proofread. Go team!

**Comment by rebeccarubenstein** [comment]
@nevanscott All the text has been updated/proofread — if possible, can you push the changes (sans art) to the preview site, so Taylor and I can proofread the pieces a final time when we're available during the day? (This is also so we can both work on setting up posts for social media and don't have to do that at the last minute — we'll be using a lot of pull quotes, and it's easier to nab them from the text on the preview site itself.)

@ftpavlik Can you update the author bios on all your pieces (publications still need < cite> tags, etc.), then comment here and let Nevan know so he can push those changes?

**Comment by nevanscott** [comment]
Don't ask why I'm up, but I actually had posted the drafts with somewhat final art Saturday evening to the preview site.

**Comment by rebeccarubenstein** [comment]
I'm going to need you to push the changes again, since I made edits to a bunch of em dashes, and I think the spacing might be a little crazy on some of the pieces.

P.S. Why are you up?

**Comment by nevanscott** [comment]
Should be pushed now...

**Comment by ftpavlik** [comment]
Not sure if there's a better place for this comment, but I'm on the preview
front page and it looks like we still have "Wendy C. Ortiz" as the
interviewee in the title instead of "Edan Lepucki."

**Comment by nevanscott** [comment]
I'm closing this issue out, since all the articles are in there. Let's make new issues for more specific problems if needed.
