### ISSUE TITLE
Small Plates: Wendy C. Ortiz: Editor's Note

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#112]
I'm still working on this, but it looks like I won't be able to finish until I get home from bookstore training, which should be around 5 pm PT. I'm really sorry I'm bumping up against our deadline -- things got a little harried this week.

Other than the Editor's Note, is everything else good to go? The book cover image works?

**Comment by nevanscott** [comment]
Should be fine, just let me know as soon as you're done. I believe the image you sent worked fine, but I'll double check tonight before I consider everything wrapped. I know the image itself is fine, I just may have placed it incorrectly.

Cheers,

Nevan

**Comment by rebeccarubenstein** [comment]
@nevanscott Okay, it's in there. I'm so sorry it's taken me this long.

**Comment by rebeccarubenstein** [comment]
@nevanscott Also: in the event that you've gone to bed and don't see this until the morning, feel free to push the changes but maybe we can coordinate on having this go live? It doesn't necessarily need to be tomorrow morning; if you're able to do it at lunch time that's cool too. I will just need to coordinate social media with Ashley.

**Comment by nevanscott** [comment]
Here's the preview:

http://preview.midnightbreakfast.com

Just let me know when you'd want it pushed. Preferably before I leave in the morning... because I'd rather not have to take my computer with me tomorrow.

**Comment by nevanscott** [comment]
I'm also assigning this to you to close out if you don't have any other changes to make.

**Comment by rebeccarubenstein** [comment]
Okay, I made three small changes that need to be pushed, and then this can go live when you get up tomorrow morning. I'll send Ashley the permalink so she can do her social media thing. This looks fantastic, thank you!

**Comment by nevanscott** [comment]
OK: http://preview.midnightbreakfast.com

**Comment by rebeccarubenstein** [comment]
Looks great! Should I open another issue ticket for publishing this tomorrow, or is that what that pull ticket is for?

**Comment by nevanscott** [comment]
Yeah, that’s what the pull request is for.

**Comment by rebeccarubenstein** [comment]
Closing this then.

**Comment by rebeccarubenstein** [comment]
Reopening this because there was one sentence that didn't sit with me correctly and I needed to change it. Can you push the change? Then this will be ready to be launched and you can close this issue ticket again.

**Comment by nevanscott** [comment]
Sorry forgot to close this, but it should be up now!
