### ISSUE TITLE
Contributors Page: update

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#113]
Just a friendly reminder that the contributors page will need to be updated with Issue 2 info. Let me know if I can help with that, though it might be best if you do it, since you know who illustrated what.

**Comment by nevanscott** [comment]
@rebeccarubenstein Hey, I made a bunch of changes to this page, which in part should mean that it'll automatically get updated in the future as we add the other things in. (Wouldn't that be nice?)

It could use some design love at some point, but I think it's in pretty good shape, hoping you could check it out.

http://preview.midnightbreakfast.com/contributors/

**Comment by rebeccarubenstein** [comment]
@nevanscott To borrow McDonald's slogan: I'm lovin' it. If you're satisfied, feel free to close this out.

**Comment by nevanscott** [comment]
Cool, I will leave it alone for now. As always, I want to keep tweaking and making more changes, but some will have to wait. :)
