### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#114]
Not sure if Taylor already emailed you about this, but please make sure the section headers in the following pieces follow the style you'd like:

https://github.com/midnightbreakfast/web/blob/magazine/_src/magazine/_posts/issue002/2014-07-28-the-invention-of-history.md

https://github.com/midnightbreakfast/web/blob/magazine/_src/magazine/_posts/issue002/2014-07-28-trizas-fragments.md

https://github.com/midnightbreakfast/web/blob/magazine/_src/magazine/_posts/issue002/2014-07-28-what-remains.md

**Comment by nevanscott** [comment]
@rebeccarubenstein @ftpavlik 

I did fix these, but not in their own commit. In general I've been using h2's for these kind of headers, which in Markdown look like this:

``` md
## Header

The following paragraph.
```
