### ISSUE TITLE
Final Proofread of Issue 2 Pieces

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#115]
Once you've had a chance to do a final proofread of all of your pieces on the Preview site (and make any last-minute edits/commits), please respond to this with confirmation. I'll add Nevan to the thread and let him know he should push those changes.

**Comment by nevanscott** [comment]
Guys, don't check just yet, I am pushing a big update to the Preview site.

**Comment by nevanscott** [comment]
But it's taking me a few minutes to get it up there.

**Comment by nevanscott** [comment]
OK,most recent changes should be up:

http://preview.midnightbreakfast.com

Proof away!

**Comment by ftpavlik** [comment]
What Remains, Trizas, and The Invention of History are looking good!

**Comment by nevanscott** [comment]
@rebeccarubenstein Are you planning on doing this for your pieces on this thread as well? Or if Taylor's happy with his, should I close this out?

**Comment by rebeccarubenstein** [comment]
@nevanscott Just finished proofreading my pieces and made a few changes, so they'll need to be pushed. Feel free to close this out once that's done.

**Comment by nevanscott** [comment]
Your changes should be up on Preview now.
