### ISSUE TITLE
Invention of History Thumbnail

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#116]
If there's any way to make a thumbnail that doesn't include the Christian bible, that would be great. The piece is actually about ghettoized Jews during WWII, but since it's obviously too late to ask Lyndsey to redo the illustration (which I love otherwise), it'd be best to not highlight the bible and misrepresent the piece on the homepage.

**Comment by nevanscott** [comment]
OK, yeah, I can work on that. Good catch.

**Comment by rebeccarubenstein** [comment]
Thank you!

**Comment by nevanscott** [comment]
Alright, moved to a different section. (The last one was just the dead center of the image, btw.)

Looks better to me, and I think the colors help out as well...

http://preview.midnightbreakfast.com

**Comment by rebeccarubenstein** [comment]
I agree, and it makes the layout of the pieces look even better. Closing this one out.
