### ISSUE TITLE
Small Plates placement

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#117]
Is there a reason why our latest Small Plates is still at the top of the page? I'm assuming this is in intentional.

**Comment by nevanscott** [comment]
Hmm... I hadn't really thought about it for some reason. I'll move it down though, I'd rather the issue be up top.

**Comment by nevanscott** [comment]
@rebeccarubenstein Better now?

**Comment by nevanscott** [comment]
Sorry, just to clarify the last. If you have a look here now:

http://preview.midnightbreakfast.com

It should be much better. I'm happy with this for the placement of those for now. If you are too, feel free to close this out.

**Comment by rebeccarubenstein** [comment]
Looks great. :)
