### ISSUE TITLE
Lyndsey's illo

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#119]
You might be dealing with this already, but if there's any way to resize Lyndsey's illo so it doesn't create a giant thing of white space in Luke's piece, that would be awesome. It's lyrical prose, so it really needs to flow without a spatial interruption like that.

**Comment by nevanscott** [comment]
This is a... Trickier problem than it seems. I may simply do as you suggest and make it smaller, but ideally I'm just going to fix the way that line works. But as I say, it's being tricky.

**Comment by rebeccarubenstein** [comment]
I appreciate your diligence with this. 

As much as I love vertical illustrations, we might want to consider not allowing folks to give us such vertical illos. Ideally, they should run alongside the text but not break it up in a crazy way.

**Comment by nevanscott** [comment]
Fixed this in a kind of dumb way for now. Eventually we'll have to address this problem for real. Note to future self...
