### ISSUE TITLE
Push changes to What Remains

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#120]
@nevanscott Karissa pointed out an italics error towards the end of the piece, so I took another look and caught a period instead of a comma and an em-dash without the surrounding spaces. Changes have been committed. Please push to the site when you have the chance.

**Comment by ftpavlik** [comment]
@nevanscott Can you please merge the few changes ASAP? Karissa just wrote me about one of the other errors I already caught. Thanks!

**Comment by ftpavlik** [comment]
Hmm.., perhaps I should have actually assigned this issue...

**Comment by nevanscott** [comment]
Hey,

Sorry I didn't write earlier about this, but I've been away from my computer all day. I'll try to square it away when I get home in a bit. Please give her my apologies...

Nevan

**Comment by nevanscott** [comment]
Hey, should be fixed now.

**Comment by ftpavlik** [comment]
It's all good. Thanks!
