### ISSUE TITLE
Small Plates: Salgado/Hoffman excerpt

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#125]
Still pulling this together, but this is where our latest Small Plates lives:

https://github.com/midnightbreakfast/web/blob/smalls/_src/smalls/_posts/2014-08-08-salgado-hoffman-amor-and-exile.md

I think I may have fucked something up with the coding at the beginning, since the preview doesn't look like the others. (Maybe I accidentally deleted something and just can't figure it out?) Would you be able to take a look for me?

Also, attaching hi-res images of the book cover and also images Nicole Salgado sent that she thought we could run alongside the excerpt. I'll let you make those art calls. I don't think we need to use every image -- whatever you think is best. Just let me know if you need me to get bigger photos.

Last thing: the excerpt is a vignette titled "The Road South (September 2006)" from a chapter titled "Alienation." I used our standard language for the copyright disclaimer, but if you have any ideas of how to incorporate this information into that, let me know. (Or if we even need to; I'll probably just mention it in the intro.)

![amor cover final hi res jpeg](https://cloud.githubusercontent.com/assets/4043562/3820654/fe66ec50-1cfb-11e4-84a8-473be901698a.jpg)

![n and m south route](https://cloud.githubusercontent.com/assets/4043562/3820691/873cbb90-1cfc-11e4-85ba-00a7c89730e3.png)

![n and m south thru jalisco](https://cloud.githubusercontent.com/assets/4043562/3820695/8e147674-1cfc-11e4-937c-c85eb5d5ec72.jpg)

![low res_authors with rep gutierrez 6 13](https://cloud.githubusercontent.com/assets/4043562/3820696/95bdc772-1cfc-11e4-9522-70aef316557e.jpg)

![nicole family cadereyta 4 2013_low res copy](https://cloud.githubusercontent.com/assets/4043562/3820700/9ce0d4d6-1cfc-11e4-8a74-44510856489a.jpg)

![nicole in d c 2013](https://cloud.githubusercontent.com/assets/4043562/3820707/bb2a2bea-1cfc-11e4-9190-c27737822d38.jpg)

![nate nicole 1 2011_small](https://cloud.githubusercontent.com/assets/4043562/3820708/bfb18e24-1cfc-11e4-8ac6-92a842307476.jpg)

**Comment by nevanscott** [comment]
@rebeccarubenstein Any chance we could get a higher-resolution version of the cover?

**Comment by rebeccarubenstein** [comment]
@nevanscott Nicole and Nathaniel just emailed me back -- this is the best version they have, so hope it works:

![amor and exile cover](https://cloud.githubusercontent.com/assets/4043562/3870715/727b7aa2-20da-11e4-886c-9f945b98dbbc.jpg)

**Comment by rebeccarubenstein** [comment]
@nevanscott Still working on intro. I need to go to bed. Will wake up at 7:30 am to finish things.

Once I have everything in place, I'll let you know so you can push the current changes.

**Comment by rebeccarubenstein** [comment]
@nevanscott Everything's in there, so please push the changes when you get a chance. Also, in the preview, the text for the intro is all smooshed together...not sure why that is or how to fix it.

**Comment by nevanscott** [comment]
Take a look here, and let me know if it's good to go?

http://preview.midnightbreakfast.com

**Comment by rebeccarubenstein** [comment]
Three things:
1. The bios are missing, even though they're included in the preview in GH (and they're in the editor).
2. Is there any way the book image on the homepage can be a sliver of the title?
3. There's a paragraph that's spaced weirdly, even though it looks fine in the editor. Here's a screenshot:

![screen shot 2014-08-12 at 9 08 34 pm](https://cloud.githubusercontent.com/assets/4043562/3901161/9c314f22-229f-11e4-958a-aaaaf48b423a.png)

Other than that, everything looks ready to go.

**Comment by nevanscott** [comment]
I'm working on fixing #'s 1 and 3, but I can't really do anything about 2 right now. Like I said, I really need to overhaul how these get laid out, and it's just too much work to be worth it right now...

**Comment by rebeccarubenstein** [comment]
Okay, don't worry about no. 2 for now. Thanks for working on the others.

**Comment by nevanscott** [comment]
I don't like how it looks either, but I have a headache and just can't futz around enough right now to improve it without it being a weird jacky thing. I wish I could.

**Comment by rebeccarubenstein** [comment]
It's fine. I think so long as the other two are fixed, everything's good. I think Nicole and Nathaniel are just grateful we're featuring their book.

**Comment by nevanscott** [comment]
Ok, how's that now?

(P.S. I realized the other Small Plates bios were missing as well, after some changes I made for Issue 2... oops...)

**Comment by rebeccarubenstein** [comment]
Sorry, I noticed one more thing that I needed to change. Can you push it? Then this will be ready to go.

When do you want to publish it on the site? I feel like we can put it up tonight, unless you know when you're going to wake up tomorrow morning and Taylor and I can schedule social media to coincide.

**Comment by nevanscott** [comment]
OK, I think I'll go ahead and publish it to the main site now, since I don't know when I'm getting up in the morning... I published your changes as well.

**Comment by nevanscott** [comment]
Should be up in a couple of minutes.

**Comment by rebeccarubenstein** [comment]
Cool, thanks! Closing this out.
