### ISSUE TITLE
Push changes and publish 2014-08-19-kelman-if-it-is-your-life.md

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#128]
I think this is good to go as long as the corrected overtitle (which I cribbed from the Amor & Exile code) looks good. Thanks!

**Comment by nevanscott** [comment]
Cool, I'll double-check it. When would you want it to go live?

**Comment by ftpavlik** [comment]
Let me take another look once the changes have been pushed and then I saw let's go for it.

**Comment by nevanscott** [comment]
Should be up now. Can you confirm?

**Comment by ftpavlik** [comment]
Looks good. One last thing: can you link the cover image to the book page (http://www.otherpress.com/books/life/)? I'm not sure how to code that for an inserted image.

**Comment by nevanscott** [comment]
OK, should be up and launched to the main site now…  

N

**Comment by ftpavlik** [comment]
Thank you!

**Comment by ftpavlik** [comment]
Rebecca just pointed out that the bio is missing... Can you add that in ASAP? Thanks!

**Comment by nevanscott** [comment]
Hey, sorry for the delay, long long day with much wariness. I'm working on getting this up at the moment, should be up in about 5-10 minutes.

Also, I realized that I had made a change to how this works without updating the wiki entry, so this is my bad, not yours. I just updated the wiki to reflect the change as well.

**Comment by nevanscott** [comment]
It's up now, and the wiki btw is here, so you can see the change:

https://github.com/midnightbreakfast/web/wiki/Small-Plates

**Comment by ftpavlik** [comment]
You have this uncanny ability to respond to these issues moments before I check to see if you have. Thank you!
