### ISSUE TITLE
Set-up for Lincoln's Michel's pieces

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#131]
@nevanscott I hate to ask, but since Lincoln's pieces are unique in that they're going to be published together, do you think you can set these up? I'll be happy to take the reins on formatting them/adding Lincoln's bio, but I'm not quite sure how you'd like them added to the system, and I think it'll save time if you're able to set them up this time around.

The stories live here and are called "Lawn Dad" and "One Thing After Another":

https://drive.google.com/?tab=mo&authuser=0#folders/0B00sYUSV_FmnY1dpQWdjbGtqUEk

"Lawn Dad" should go first, followed by "One Thing After Another."

**Comment by nevanscott** [comment]
Ok, I'll take a whack at it.

**Comment by rebeccarubenstein** [comment]
Thanks! Just let me know once it's set up so I can do the .05% formatting it needs.

**Comment by nevanscott** [comment]
Put in the initial version.

**Comment by rebeccarubenstein** [comment]
This looks good. Closing the ticket and opening a separate one for art stuff.
