### ISSUE TITLE
Mairead Case's piece: title

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#134]
Since this a series of vignettes functioning as an excerpt, how do you want to handle the title on this?

**Comment by nevanscott** [comment]
I'm not sure what you mean... Can you give me an example of how we might present it?

**Comment by rebeccarubenstein** [comment]
Like, do we want this titled _See You in the Morning_ or something like "an excerpt from _See You in the Morning_"?

**Comment by rebeccarubenstein** [comment]
Making an exec decision since this has gotten dropped and is probably low priority -- we'll just leave the title as is.
