### ISSUE TITLE
[Issue 3] TOC

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#135]

**Comment by nevanscott** [comment]
I added in a few (see above commit), but the others will need to be listed as well, and ordered.

**Comment by rebeccarubenstein** [comment]
@nevanscott Can you link me to where this lives?

**Comment by nevanscott** [comment]
https://github.com/midnightbreakfast/web/blob/magazine/_src/_data/issues.yml

**Comment by nevanscott** [comment]
All 6 are in now, but we should keep this around while we think about the order.

**Comment by rebeccarubenstein** [comment]
I've updated the TOC, but I won't really know how I feel about it until I've had a chance to see it with whatever image you're intending to use for See You in the Morning.

**Comment by rebeccarubenstein** [comment]
@nevanscott Once you're able to crop that image and push it to the preview site, let me know. It's possible I might want to shift things around one more time. The colors are weirdly bouncing for me.

**Comment by rebeccarubenstein** [comment]
If you need to go to bed before I get home, could you just make sure it looks nice and the colors aren't too severe against one another? I'd like, if possible, for Lincoln's piece and Merritt's interview to stay where they are. Thank you!

**Comment by nevanscott** [comment]
I put in the new thumbnail (I picked the octopus) and am just working on a new crop for the thumbnail of Melody's piece. I think I'm happy with the order, but I'll let you take a last gander.

**Comment by rebeccarubenstein** [comment]
Okay, had a chance to look at the TOC. I'm happy with the order. LET'S DO THIS.
