### ISSUE TITLE
Art

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#142]
Question about the art: are you still working on placement? Because I noticed all the illustrations are aligned right, rather than some being aligned right, some being enlarged and centered/placed before the text, etc.

Some of these illos are gorgeous (like the ones for Lincoln's, Molly's, and Melody's pieces), so it'd be great to have those featured more prominently.

**Comment by nevanscott** [comment]
Yeah, I’m still working on that as well.

**Comment by rebeccarubenstein** [comment]
Figured, but wanted to check in. :)

**Comment by nevanscott** [comment]
By the time you get up, this should be mostly reconfigured.

**Comment by nevanscott** [comment]
(I'm treating Mairead's piece as a separate issue.)

**Comment by rebeccarubenstein** [comment]
Art looks great!
