### ISSUE TITLE
See You in the Morning: images

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#144]
Per your request, I've indicated in the editor where the images should be placed. If it's okay, can we not use the image of the hand with the steering wheel and the cake? The cake, especially; not sure what's happening with cakes for this issue, but in the vignette, the icing is blue, so the illo doesn't make much sense.

**Comment by rebeccarubenstein** [comment]
You can reply here once you've done this and I'll quickly scope this out, either on break or when I'm at the register at work.

**Comment by ftpavlik** [comment]
@rebeccarubenstein @nevanscott Just want to jump in here to ask that you let me know when this is updated so I can update the image on the newsletter. Also, if the illustrations are being spaced out, should the credit line read "Illustrations by" instead of "Illustration by"?

**Comment by nevanscott** [comment]
I've stuck with Illustration by in the past, so for now I'm going to leave it in the interest of getting this done. I'm open to the idea though.
