### ISSUE TITLE
Stay: formatting issue

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#145]
Noticed a weird instance of spacing with this piece. Double-checked in the editor, but things look okay there, so not sure what's going on. Here's what it looks like on the preview site right now:

![screen shot 2014-08-27 at 10 52 40 am](https://cloud.githubusercontent.com/assets/4043562/4064624/2ef619ae-2e13-11e4-8154-07e17aeb0a95.png)

**Comment by nevanscott** [comment]
I think Taylor had already fixed this, just hadn't been pushed.
