### ISSUE TITLE
Changes to articles

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#147]
@nevanscott  Taylor and I have made various changes/minor fixes to our pieces, which should be completely proofread now. Please push those changes and then reply here once you've done so/updated the preview site, so we can each do final read-throughs and give you the a-okay.

**Comment by nevanscott** [comment]
@rebeccarubenstein @ftpavlik Both of your changes should be live on the Preview site now.

**Comment by rebeccarubenstein** [comment]
@nevanscott My pieces look great and are ready to go.

@ftpavlik Can you look over yours one last time, then confirm here and close the ticket if everything looks okay on your end?

**Comment by ftpavlik** [comment]
@rebeccarubenstein @nevanscott My pieces look good!
