### ISSUE TITLE
Kael Alford link?

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#149]
Do you have any ideas?

**Comment by rebeccarubenstein** [comment]
Kael, very conveniently, has a website: http://kaelalford.sites.livebooks.com/

:)

**Comment by rebeccarubenstein** [comment]
Added that info in, so once you push the change she should show up on the Contributors page, but we should make sure her name is linked in her credit at the bottom, too.

**Comment by nevanscott** [comment]
Should be good to go.
