### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#15]
For my bio, can you amend it slightly? Let's have it read: [Rebecca](http://rebeccarubenstein.com) likes to make words work. In addition to _Midnight Breakfast_, she is also the interviews editor for [The Rumpus](http://therumpus.net) and a former contributing editor for the short-lived but wonderful [STET](http://stet.editorially.com). She resides in San Francisco and can often be found [thinking aloud](http://twitter.com/rrrubenstein) on Twitter. The way to her heart is truly through breakfast (or brunch, if it’s the weekend).

The Rumpus and STET should also be italicized, as per everyone else's bios.

**Comment by nevanscott** [comment]
should be updated

**Comment by rebeccarubenstein** [comment]
Can you italicize Midnight Breakfast, por favor?

**Comment by nevanscott** [comment]
OK, is that better?

**Comment by rebeccarubenstein** [comment]
Yep
