### ISSUE TITLE
Contributors Page

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#158]

**Comment by nevanscott** [comment]
Kinda donnish but not perfect. I'll need to come back and revisit.

**Comment by nevanscott** [comment]
I think I'm going to leave this as it is for now. I know it isn't ideal, but I'm trying not to go crazy rewriting 175 lines of code right now...

**Comment by nevanscott** [comment]
@rebeccarubenstein Have a look and let me know if you're okay with what's up now. It will just eat up time to try to do any better than this right now, and it doesn't seem worth it to me at the moment...

**Comment by rebeccarubenstein** [comment]
This looks fine to me, though you should tell me (maybe outside of an issue ticket) why you decided to shirk the alphabetization in favor of aligning writers with their artists.
