### ISSUE TITLE
Push changes to 2014-08-27-stay.md

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#163]
@nevanscott Melody requested I add a line to her bio. Can you please push the change when you have the chance?

**Comment by nevanscott** [comment]
Should be up… Can you check and close this out?  

Thanks,
Nevan

**Comment by ftpavlik** [comment]
@nevanscott It's up, but I forgot to close the italics... Can you please push again?

**Comment by nevanscott** [comment]
Up.
