### ISSUE TITLE
Additional Copy for Submissions Page (please see asap)

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#165]
If you let me know where the Submissions Page copy lives, I can make these changes myself and then let you know once they're ready to be pushed.

Otherwise, can you please add the following copy:

**If you're submitting to our October issue...**

We're pleased to announce that Issue Five will be our first themed issue, featuring work that tackles the idea of "breaking down the barriers between the real and the unreal." We'll be accepting nonfiction and fiction submissions for this issue (though our preference is for nonfiction) until **Friday, September 26th**. Please follow the instructions above and also add "Halloween Issue" to the subject line of your email. Pieces submitted after the deadline will be considered for future issues.

---

It should be placed after this submissions guideline:

![sub guideline](https://cloud.githubusercontent.com/assets/4043562/4223091/e723f950-3918-11e4-9f65-ad0a28f42f41.png)

**Comment by nevanscott** [comment]
How's that?

**Comment by rebeccarubenstein** [comment]
It's not showing up on the preview site for some reason...

**Comment by nevanscott** [comment]
It's on the live site, sorry I didn't clarify!

**Comment by rebeccarubenstein** [comment]
Looks great! Thank you so much for making it happen so quickly. :)

I'm not able to log into GH from work, so would you be able to close this
ticket?
