### ISSUE TITLE
MariNaomi's piece

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#169]
Can you let me know once you've uploaded this to Craft and dealt with the images? I can then go in and make sure everything is squared away editorially.

**Comment by rebeccarubenstein** [comment]
@nevanscott What should the genre for MariNaomi's piece be? Comics?

**Comment by rebeccarubenstein** [comment]
@nevanscott Also, we need to make sure to put the subtitle in her piece. It should be:

(if you happen to be a person of another color)

**Comment by rebeccarubenstein** [comment]
@nevanscott I've done all my editing on this, so feel free to go in and do your thang. Also, please see above comments.

**Comment by nevanscott** [comment]
OK, things are looking better to me at the moment...

**Comment by rebeccarubenstein** [comment]
Oh man, this looks so, so awesome. Style question: should I insert a horizontal rule between MariNaomi's introduction and the cartoonist's commentary? I feel like yes, but want to get your thoughts. Also, again, genre question: should we label this comics? Nonfiction? Nonfiction / Comics?

**Comment by rebeccarubenstein** [comment]
Ignore genre question, just noticed you addressed that. Sorry!

**Comment by nevanscott** [comment]
If you'd like to try out an <hr>, go right ahead. I think it could be nice.

I was even considering placing them between each illustrators's entry...

**Comment by ftpavlik** [comment]
@rebeccarubenstein I was about to create an issue when I noticed this one, so I figured I'd jump in and keep things streamlined. I'm giving this a read right now and I'm wondering if we should change MariNaomi's byline at the top to "Edited by." This is how the Believer does it for their comics page.

**Comment by rebeccarubenstein** [comment]
@ftpavlik She wrote the opening as a brief essay, so I'd like to just leave this as a regular byline (also, though she culled all these quotes, this was really edited by me and Lauren).

**Comment by ftpavlik** [comment]
I think the "edited by" for collections like this is more commonly used for the person who selected the artists within (or maybe curated by would be better?), but I'm fine leaving it the way it is, as I think MariNaomi's role is clear either way.

**Comment by rebeccarubenstein** [comment]
@nevanscott Added horizontal rules to the piece. Take a look and see what you think? Happy to go either way, but I think they look nice dividing the artists.

**Comment by nevanscott** [comment]
Yeah, I think the rules help. Let's keep them.
