### ISSUE TITLE
In-line style issue

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#172]
Please fix the in-line style. (Whatever that means.)

**Comment by rebeccarubenstein** [comment]
Just a heads up that the in-line style issue is affecting cited text in Small Plates as well. Example:

![screen shot 2014-09-28 at 2 22 18 pm](https://cloud.githubusercontent.com/assets/4043562/4435748/97604ac2-4755-11e4-8950-ec6955007904.png)

**Comment by nevanscott** [comment]
@rebeccarubenstein OK, I think I removed all of these...

**Comment by rebeccarubenstein** [comment]
Looks good.
