### ISSUE TITLE
Proofreading pieces and Small Plates

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#174]
Let's use this space to communicate and confirm the proofreading of our pieces. We'll also need to proofread the different Small Plates; I'd like to split those up, as well, depending on who was responsible for them. Once you've had a chance to proofread your pieces/Small Plates, just comment here. I'll do the same (I've already proofread my pieces but not Small Plates).

Nevan and I looked into it and realized the glitch has something to do with < em > tags. He's going to work to fix the problem from here on out, but for now, we should just make sure everything looks okay prior to publishing. Nevan's also aware that some of the bios look strange and is working to write code that will automatically fix everything on that end.

**Comment by ftpavlik** [comment]
@rebeccarubenstein My Small Plates and previous pieces have been proofread. Caught a few missing spaces by italics, but otherwise everything looks good. I also fixed the weird italics formatting in the bios of Landis and Kelman. I think we're good to go!

**Comment by rebeccarubenstein** [comment]
Awesome. I'm having brunch with Cori in an hour but I'll be online to finish things off this afternoon. Still writing the Letter from the Editor, but if you haven't already, you might want to ping Nevan and get art from him so you can do your newsletter thang and also queue up Facebook posts (unless you can't do that without live links?). I'll drop another comment in here and close the ticket once I've had a chance to do my final proofs of Small Plates, but my pieces are fine.

**Comment by rebeccarubenstein** [comment]
All read! Nevan is still working on uploading MariNaomi's piece, but that's a separate issue ticket, so I'm going to close this one.
