### ISSUE TITLE
Letters from the Editor

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#175]
I think you said you'd set these up for Issues 1-3, so I'd be able to look at them and set mine up for Issue 4.

**Comment by rebeccarubenstein** [comment]
@nevanscott  Actually, I'm gonna take care of this. Taking this off your plate.

**Comment by nevanscott** [comment]
I just put one in for Issue 1, so that you can at least do the same for the others.

**Comment by rebeccarubenstein** [comment]
SIMPATICO.

**Comment by nevanscott** [comment]
I had to change some setup stuff, but hopefully it makes sense.

**Comment by rebeccarubenstein** [comment]
PS I've gotta finish this letter before Taylor kills me, so let me know if you need me to look at anything, but anything that needs an additional hand from me is gonna have to be on hold for an hour or so.

**Comment by nevanscott** [comment]
OK
