### ISSUE TITLE
Image fixes in See You in the Morning

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#177]
The internal images for "See You in the Morning" need to be fixed/resized. Maybe you have a good solution for doing this quickly?

**Comment by nevanscott** [comment]
Have a look.

This is the thing: I know there's an image insert option in that text field, but it isn't very flexible. So images work differently than that. Maybe if you take a look it will make more sense?

**Comment by rebeccarubenstein** [comment]
Looks great! And thanks, I'll get the hang of this image thing eventually...
