### ISSUE TITLE
Photographer bylines

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#178]
For our interviews with Wendy C. Ortiz, Merritt Tierce, and Thomas Page McBee, and "Orange Valley Lodge 13," I noticed the "Illustrated by" byline automatically generates. Can you make sure these bylines say "Photography by"? Not sure if we'll have to create a separate category for photographers or if you can just write some code to do a quick fix on all these for now (and we can create the category during clean-up later). Thanks!

**Comment by nevanscott** [comment]
I'll look at this as soon as I can, prioritizing Issue 4 for now, so that we have everything set for it...

**Comment by rebeccarubenstein** [comment]
Cool. Just make sure this gets done, since Thomas's interview is part of Issue 4. :)

**Comment by nevanscott** [comment]
I think these are working now.

**Comment by rebeccarubenstein** [comment]
Yup, they're all there. Thanks!
