### ISSUE TITLE
Image uploads

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#180]
Hey @nevanscott , can you please let me know when the Issue Four images are uploaded? I need to load them into the newsletter.

**Comment by nevanscott** [comment]
@ftpavlik @rebeccarubenstein I'm going to be working on this for the next little bit, to get it done first.

**Comment by nevanscott** [comment]
Alright guys, images are in, although I may go back and change some of the thumbnails (cropping-wise). But Taylor— you don't use the thumbnails, right, you use the fuller images?

**Comment by ftpavlik** [comment]
@nevanscott That's right. Are you adding them to the dropbox or should I just download them from the cms?

**Comment by nevanscott** [comment]
@ftpavlik I'll upload what I've got to the Dropbox, but you can also pull from the Live Previews. Those are full size for now.
