### ISSUE TITLE
Issue 4 Ed Letter

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#181]
Hey @rebeccarubenstein can you please let me know when your ed letter is finished so I can load it into the newsletter?

**Comment by rebeccarubenstein** [comment]
Dealing with it as we speak.

**Comment by rebeccarubenstein** [comment]
I will be done with this in 15 minutes tops.

**Comment by rebeccarubenstein** [comment]
Proofreading.

**Comment by rebeccarubenstein** [comment]
https://docs.google.com/document/d/1SoVOGt-vM4oCrVpx4odF9qiBV7qUtbkObMMkPvdEK7U/edit?usp=sharing

**Comment by rebeccarubenstein** [comment]
Adding this to our CMS, but wanted you to have the text now.
