### ISSUE TITLE
Order of pieces

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#182]
The pieces are ordered the way I think they should go. The only switch I'd make (if we were thinking of one switch) is to swap the interview with Thomas with "Airport Hotel Ghost Tour." Otherwise, the colors play off one another really nicely.

One thing: can you recrop the thumbnail image for "Things I Lost in the Move" so the head's not chopped off?

**Comment by nevanscott** [comment]
re the order: I'm fine with it if you are.

I opened a new issue for the thumbnail #186

**Comment by rebeccarubenstein** [comment]
Yeah, I like it.
