### ISSUE TITLE
New thumbnail crop for "Things I Lost in the Move"

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#186]

**Comment by nevanscott** [comment]
@rebeccarubenstein I did a new thumbnail, but I can't crop it in such a way that the Issue Number badge won't cover the head sometimes when it's in that position. Maybe we should rearrange the order?

**Comment by rebeccarubenstein** [comment]
Unless it's really bothering you, I think the crop of part of the head is fine. Just so long as it's not the whole head. Does it bother you enough where you'd like to change it?

**Comment by nevanscott** [comment]
I think I'm ok either way. Thought it might bother you. I'll close this out.

**Comment by rebeccarubenstein** [comment]
Nah, just so long as her head's not a number. :)
