### ISSUE TITLE
[Issue 8] Header for Rahawa Haile's piece 

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#189]
Given the way things are set up with Craft, is there any way to make the titles of Rahawa Haile's stories appear in the header of the actual piece itself? The titles are:
1. The Lives and Loves of Intricate Cakes 
2. When The Seltzer's Like "Nah" and You're Like "Oh Please, Please Be Cold" and the Seltzer's Like "Nah"

Right now, the header obviously says "Two Shorts" (which Rahawa verified is fine for the homepage).

**Comment by nevanscott** [comment]
@rebeccarubenstein Should be good to go!
