### ISSUE TITLE
Art for Issue 8

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#193]
Please add all Issue 8 art to Craft and ping me once it's ready so I can set the order of the pieces for the homepage.

**Comment by nevanscott** [comment]
@rebeccarubenstein These should all be in, and I also addressed the issue you brought up in your email. I'm sorry I hadn't followed up with you before. I still don't think the cartoon figure would have been offensive, but we should have checked with the author probably, and now it's too late. So I went ahead and cut it like you wanted.
