### ISSUE TITLE
[Contributors Page] Redundant names

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#22]
We should remove all the names of the contributors because all of the bios start with their names. No moar namez.

**Comment by nevanscott** [comment]
Thanks for noting this

**Comment by nevanscott** [comment]
OK, I decided to try out something simpler, and added in an intro paragraph that could probably use help. At least there's no redundancy.

I think we should revisit this page and add bios for everyone, after we get bios for the illustrators. What do you think?

**Comment by rebeccarubenstein** [comment]
Change the copy to: We’d like to thank all of our writers and illustrators, all of whom have helped make for a wonderful launch issue of _Midnight Breakfast._ If you like their work here, we encourage you to take a gander at more of what they’re up to.

Otherwise, I think this looks good, and I like your idea to revisit and add the bios again once we have illustrator bios.

**Comment by nevanscott** [comment]
Should be changed. Any other thoughts?

And can you make a separate issue for the post-launch updates? I'm gonna set up some milestones for these things.

**Comment by rebeccarubenstein** [comment]
Sure thing. No other thoughts at the moment.
