### ISSUE TITLE
[An Ongoing Conversation] Need internal <hr>s

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#23]
Not sure if you're planning on fixing this, but the line between the first section and the last paragraph looks a little awkward spanning the length of the column. For pieces, we should probably have a shorter line to break up sections (unless we're using them to separate story from someone's bio or, in the case of "A Prayer for Glampers," the disclaimer at the end).

**Comment by nevanscott** [comment]
good to note

**Comment by nevanscott** [comment]
@rebeccarubenstein I don't remember what the title of this was originally, but I made some changes that I think resolve what you're talking about?

**Comment by rebeccarubenstein** [comment]
Yeah, I think you've got it covered.
