### ISSUE TITLE
[Homepage] Order of Pieces

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#24]
Here's my recommended order:

From top left: Northern Souls, The Aqiqah, The Russian Coat
From bottom left: So Funny It Hurts, Callie, A Prayer for Glampers

**Comment by nevanscott** [comment]
ok, they are in that order now, I think it makes sense...

**Comment by rebeccarubenstein** [comment]
Hmm, it's caching. I need to wait for it to catch up.

**Comment by nevanscott** [comment]
it wasn't you, it was me, same problem as before, don't update because the file size was the same :)

**Comment by rebeccarubenstein** [comment]
Okay, I see it now. Looks great!
