### ISSUE TITLE
[Campaign] Add Mailchimp form

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#25]

**Comment by nevanscott** [comment]
this is added but will need to be made prettier

**Comment by rebeccarubenstein** [comment]
Looks good. Are you still planning on putting a wee box on the homepage?

**Comment by nevanscott** [comment]
This is almost done with styling.

**Comment by nevanscott** [comment]
OK, this is now officially "good enough". We can revisit later when I'm feeling picky.

**Comment by nevanscott** [comment]
@rebeccarubenstein Will you take a look and try out the form for yourself?

**Comment by rebeccarubenstein** [comment]
Seems to be all good. I'm subscribed and everything!
