### ISSUE TITLE
[Articles] Add bios at end of each piece

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#26]
Will you be adding bios at the bottom of each piece? This is usually the trend/tradition of lit mags, to have bios on the pages themselves and also contributors pages.

**Comment by nevanscott** [comment]
yeah, just haven't gotten to it, good to have it captured here

**Comment by rebeccarubenstein** [comment]
Cool.

**Comment by nevanscott** [comment]
they are there now, separate issue #33 for formatting

**Comment by nevanscott** [comment]
@rebeccarubenstein Can you confirm that they're all present and if there are any copy issues file separate bugs?

**Comment by rebeccarubenstein** [comment]
All there, thanks
