### ISSUE TITLE
[Homepage] Images

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#27]
You're probably in the process of fixing this, but if there's any way we can get Eric's photo resized so that at least part of the Scrabble tile holder thingy is visible, that would be great. Looks a little strange with just the tiles.

**Comment by nevanscott** [comment]
OK, the thumbnails for Callie's Interview and Eric's piece should be updated now.

**Comment by rebeccarubenstein** [comment]
Hooray, it doesn't look like she's being scalped! Good work.
