### ISSUE TITLE
[Homepage] Quippy thing about us being at AWP

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#28]
If you can fit it now, here's some copy for you. (You were supposed to write it, but I have a hunch it got buried beneath more pressing matters.) I think this can also go on the site later, like after you've landed. Anyway:

Editors Rebecca Rubenstein and Nevan Scott are heading to Seattle! Catch them at AWP 2/26-3/1.

**Comment by nevanscott** [comment]
I'm thinking this will go in the footer that I still need to give some love and attention to... Do you think that would be okay?

**Comment by rebeccarubenstein** [comment]
Hmm...I'm just worried people might not see it. But I'll let you do your thing and then let you know if it makes sense after all (or doesn't).

**Comment by nevanscott** [comment]
Any ideas where to put this at this stage in the game? I'm kind of out of ideas...

**Comment by rebeccarubenstein** [comment]
Now that you've got this lovely footer, I'd say you can drop it below our social media. Maybe italicize it or something?

**Comment by nevanscott** [comment]
OK I added, I think it works. Can you check?

**Comment by rebeccarubenstein** [comment]
Perfect!
