### ISSUE TITLE
[About Page] Edit to copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#31]
I was reading this ("Please check back, or sign up for our newsletter to be notified of when we’ve opened shop again") and it didn't quite sound right. Please amend it to: 

Please check back, or [sign up for our newsletter](http://midnightbreakfast.com/campaign) to be notified once we've opened shop again.

**Comment by nevanscott** [comment]
OK, should be fixed. Can you confirm?

**Comment by rebeccarubenstein** [comment]
All good, thanks
