### ISSUE TITLE
Art Not Centered

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#32]
In Chrome, the art isn't centered in Jason's piece:

![screen shot 2014-02-25 at 11 42 48 pm](https://f.cloud.github.com/assets/4043562/2267574/cea07ba0-9eb9-11e3-8c7a-a084c61fab11.png)

And art needs to be added to Ben's piece.

**Comment by nevanscott** [comment]
Centering should be fixed.

I made a separate issue for Glampers #35

**Comment by rebeccarubenstein** [comment]
Looks great, thanks
