### ISSUE TITLE
Separation Between Text and Bios

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#33]
Not sure if you were planning on doing this, but there should be a line of some kind separating text from bios at the end of each piece.

**Comment by nevanscott** [comment]
Added in a line.

**Comment by rebeccarubenstein** [comment]
Something still doesn't look right. Maybe there needs to be a space increase between the line and the bios, so the regular text and the bio text aren't so close?

**Comment by nevanscott** [comment]
Is that better?

**Comment by rebeccarubenstein** [comment]
Yep, thanks
