### ISSUE TITLE
[Campaign Page] Amended Copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#34]
Please amend the copy to read:

Hi there! Hopefully you’ve already had a chance to enjoy our first free, fully illustrated issue of _Midnight Breakfast_. We’ve funded this issue ourselves in conjunction with the launch of our fundraising campaign to help us keep the magazine running the way we originally envisioned. We want to continue to publish a free journal that provides a space for a diverse group of writers and artists, and also pay all of our contributors. To do this, we’re going to need a lot of help. 

If you want to find out when the campaign begins and get any other _Midnight Breakfast_ news, sign up for our mailing list below. We hate any spam that doesn’t come in a can, so rest assured that you’ll only get _Midnight Breakfast_-related emails. Thanks for your interest!

---

How does that look?

**Comment by nevanscott** [comment]
I made the change, I think it reads better in your new version.

Remaining question: What about the title of this page?

**Comment by rebeccarubenstein** [comment]
One more fix: We want to continue to publish free issues, while providing a space for a diverse group of writers and artists and also paying all of our contributors.

Here are my thoughts re: a title: Keep Us Running

Do you like that?

**Comment by nevanscott** [comment]
I made those changes, so you can see.

What about something like "Keep the Conversation Going"?

**Comment by rebeccarubenstein** [comment]
I like it. Let's do it.

**Comment by nevanscott** [comment]
OK, changed it, what do you think?

**Comment by rebeccarubenstein** [comment]
Yep, looks good
