### ISSUE TITLE
[Glampers] Add illustrations

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#35]
separated out from #32

**Comment by nevanscott** [comment]
Hmm... well, there's something, but I need to revisit, maybe use a different combination.

**Comment by rebeccarubenstein** [comment]
I think it should be one image at the top. Resist the temptation to crowd the words – they need to speak for themselves.

**Comment by nevanscott** [comment]
OK, I simplified...

**Comment by rebeccarubenstein** [comment]
Looks great
