### ISSUE TITLE
Design Footer thingamajig...

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#36]
Do yo thang.

**Comment by nevanscott** [comment]
OK, there's a footer now, can you take a look?

**Comment by nevanscott** [comment]
What do you think? Approved?

**Comment by rebeccarubenstein** [comment]
I'm into it! Thanks for taking my advice. Sometimes it's okay, right?

**Comment by nevanscott** [comment]
Yes of course, I need it when I'm blocked sometimes
