### ISSUE TITLE
[So Funny It Hurts] Block Quotes

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#37]
What happened to the block quotes?

**Comment by nevanscott** [comment]
It got changed to not using block quotes in Editorially at some point, and I haven't had time yet to comb through.

If you think the italics look okay for now, maybe this would make sense to revisit post-launch?

Or maybe we should just do it... I'm gonna have to come up with styles for blockquotes as well...

**Comment by rebeccarubenstein** [comment]
How much of a hassle is it for you to do? I want the text to look as clean as possible, so I'd prefer to launch with block quotes intact. Not too fond of all this italics business.

Ugh, Editorially, WHY.

**Comment by nevanscott** [comment]
OK, I took a whack, have a look.

**Comment by rebeccarubenstein** [comment]
Nice whacking. I'm tempted to say the block quote line should be defined a wee bit more – it's almost too subtle – but your call.

**Comment by nevanscott** [comment]
Do you like it better now?

**Comment by rebeccarubenstein** [comment]
Yeah, that's a lot better. Closing this one out!
