### ISSUE TITLE
"Northern Souls"

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#4]
"Internet" should be "internet."

**Comment by nevanscott** [comment]
should be good now

**Comment by rebeccarubenstein** [comment]
Hmm...I've checked both mobile and desktop sites and neither seem to be different.

**Comment by nevanscott** [comment]
can you check again now? I think it didn't sync because the file size didn't change. :8ball:

**Comment by rebeccarubenstein** [comment]
Fixed now for sure!
