### ISSUE TITLE
[Campaign] Name of Page

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#40]
Would it be more apt to actually call this Donate? Do you think more people would click on it? While Campaign is obviously descriptive in terms of the campaign itself, I'm not sure the title sends an immediate and clear message about what it is and why anyone should click on it.

**Comment by nevanscott** [comment]
Makes sense to me, I made the change. See what you think.

**Comment by rebeccarubenstein** [comment]
Rad, looks great.
