### ISSUE TITLE
Send Rebecca PNGs for Facebook Page

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#44]
Please send me a .png of Midnight Breakfast, white text on black.

Also, please send me a .png of An Ongoing Conversation. (again, white text on black)

**Comment by nevanscott** [comment]
Do you know what sizes these are going to be presented at? If not, can you maybe send me a screenshot of where these are going?

**Comment by rebeccarubenstein** [comment]
No clue on the sizes, but here's a screencap of The Rumpus page, to give you an idea of what it'll look like once it's set up:

![screen shot 2014-02-26 at 3 09 41 am](https://f.cloud.github.com/assets/4043562/2269279/9461853e-9ed6-11e3-8380-571eaa13f730.png)

So, I was thinking Midnight Breakfast for the banner, and then An Ongoing Conversation for that little square.

**Comment by nevanscott** [comment]
How are these?

![photo inverse](https://f.cloud.github.com/assets/72936/2269618/3011a06c-9edd-11e3-927f-43a049021f1d.png)
![photo](https://f.cloud.github.com/assets/72936/2269619/302d884a-9edd-11e3-92d8-701a71d7487b.png)
![black](https://f.cloud.github.com/assets/72936/2269620/303085a4-9edd-11e3-81e4-25aa5f6baaf5.png)
![artboard 1](https://f.cloud.github.com/assets/72936/2269621/3034addc-9edd-11e3-985b-7126573fc46b.png)

**Comment by rebeccarubenstein** [comment]
These are great, thanks!
