### ISSUE TITLE
Set up General Contact Email Address

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#45]
I think this got buried. Should probably be hello@midnightbreakfast.com.

For our About page, can you add the following text under Submissions Info (it should go after the other text):

For all other queries, please drop us a line at [link to general email].

**Comment by nevanscott** [comment]
I think this is all set up. Can you confirm that it looks right on the page, and that you got my test email?

**Comment by rebeccarubenstein** [comment]
We are go on all fronts.
