### ISSUE TITLE
[Homepage] Callie

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#47]
One last nit-picky thing: I've been dwelling on this for a while, and I think the title should say In Conversation with Callie Collins on the homepage. What do you think? It looks really weird with just her name.

**Comment by nevanscott** [comment]
OK, I tried it. Have a look at it small. I think it's still ok in terms of design with the longer title, and you're right that it's clearer.

**Comment by rebeccarubenstein** [comment]
Looks good to me, small and large.
