### ISSUE TITLE
[Donate page] Amend copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#52]
The following:

We’ve funded this issue ourselves in conjunction with the launch of our fundraising campaign to help us keep the magazine running the way we originally envisioned. We want to continue to publish free issues, while providing a space for a diverse group of writers and artists and also paying all of our contributors. 

Should be:

We’ve funded this issue ourselves in preparation for the launch of our fundraising campaign to help us keep the magazine running the way we originally envisioned. We want to continue to publish exciting work from a diverse group of writers and artists, and we want to pay all of our contributors.

**Comment by nevanscott** [comment]
Should be updated on the live site now, can you confirm?

**Comment by nevanscott** [comment]
Hey @rebeccarubenstein if this is fixed can you close it?

**Comment by rebeccarubenstein** [comment]
Oh, sorry!

**Comment by nevanscott** [comment]
No worries, thank you!
