### ISSUE TITLE
[So Funny It Hurts] Copy Edits 1

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#53]
This paragraph needs to be replaced:

Soon after, C.K. even went out of his way to involve a black caller named Kyle in his “nigger” game. Minutes before Kyle dials in, C.K. recalls a time Ronald Reagan discussed Huckleberry Finn on live television and struggled not to say “Nigger Jim” on air. In the comedian’s version of events, Reagan stumbled and said “um…Jim” instead, due to the difficulty of omitting the slur. Once Kyle was on the line, C.K. deliberately addressed him as “Um…Kyle”—effectively labeling Kyle a nigger, and chuckling with Opie and Anthony about it.

Replace text with:

Soon after, C.K. even goes out of his way to involve a black caller named Kyle in his “nigger” game. Minutes before Kyle dials in, C.K. recalls a time Ronald Reagan discussed _Huckleberry Finn_ on live television and struggled not to say “Nigger Jim” on air—at least, according to C.K. In the comedian’s version of events, Reagan stumbled and said “um...Jim” instead, due to the difficulty of omitting the slur. Once Kyle is on the line, C.K. deliberately addresses him as “Um...Kyle”—effectively labeling Kyle a nigger, and chuckling with Opie and Anthony about it.

**Comment by nevanscott** [comment]
Should be fixed, can you double-check?

**Comment by rebeccarubenstein** [comment]
Looks good
