### ISSUE TITLE
[So Funny It Hurts] Final updates

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#57]
"black and gay communities shouldn’t have to endure the same from our allies" -should definitely be "black and queer." I don't identify as gay, and that could be an easy misconception to make from the text as is.

Also: "Several white friends throughout my life have failed to grasp the heart-in-throat anxiety the phrase can cause in the moment." Should be changed to "provoke in the moment." The previous sentence has "cause" in it.

If you don't have time to make the additional changes I've suggested, I'll completely understand. But if Nevan hasn't gotten to this stuff yet, I thought I'd ask to include these.

**Comment by nevanscott** [comment]
Should be fixed.

**Comment by rebeccarubenstein** [comment]
Upset with myself that I didn't catch Eric's second edit. So obvious. These look good.
