### ISSUE TITLE
Facebook image

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#58]
Is it possible to associate an image with http://midnightbreakfast.com that will automatically upload to Facebook? People have been linking to the site, but there's no image or text associated, just a link. It's sad:

![screen shot 2014-02-26 at 1 31 39 pm](https://f.cloud.github.com/assets/4043562/2275933/75656752-9f2d-11e3-8f87-d815e63436b2.png)

**Comment by nevanscott** [comment]
Yeah, I think there's some way to do that. Maybe I can figure it out this evening...

**Comment by nevanscott** [comment]
This is fixed, right?
