### ISSUE TITLE
[Homepage] Quippy AWP Copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#59]
We should either remove it, or replace it with the following text:

To those of you we met in Seattle: thanks for making our first AWP such a blast! It was truly a pleasure, and we hope you'll consider [helping us](http://midnightbreakfast.com/donate/) in the near future.

**Comment by nevanscott** [comment]
@rebeccarubenstein I made a change to this. I think your altered copy works well.

**Comment by rebeccarubenstein** [comment]
Looks good. :)
