### ISSUE TITLE
Orange Valley Lodge #13

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#65]
Wrote you an email about this, but please delete the current version and upload [the new version](https://drive.google.com/folderview?id=0B00sYUSV_FmnU3FzSHgtYlh4SGc&usp=sharing), then let me know when that's done so I can edit accordingly. Thanks!

**Comment by nevanscott** [comment]
I'm not sure which one in that folder is indeed the new one...

**Comment by rebeccarubenstein** [comment]
Sent you an email about this so it would be clear, but it's the one titled "Orange Valley Lodge_edit2." I didn't delete the other one from the list in case we needed it for some reason.

**Comment by rebeccarubenstein** [comment]
@nevanscott Do you want me to just pull in the new text?

**Comment by nevanscott** [comment]
That would be great if you can, yes. :)

**Comment by rebeccarubenstein** [comment]
Text added. Please push the changes to the preview site so I can do a final proofread of the piece.

**Comment by nevanscott** [comment]
Should be up soon.
