### ISSUE TITLE
pieces need "types"

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#67]
This will be in the top in a block that looks like this:

```

---
layout: post
issue: 001
type: TK
title: Some Pride of Ownership
by: Dwyer Murphy
featured_image: issue1/pride/covers.jpg

---
```

The "type" shows about the title of the piece. See here:

http://preview.midnightbreakfast.com/some-pride-of-ownership/

**Comment by nevanscott** [comment]
@ftpavlik I think Rebecca is still asleep, maybe you could take a crack at this and then reassign to her when you've done?

**Comment by ftpavlik** [comment]
Apparently I can't edit on my phone... The two fiction pieces are Scumbag and Some Pride of Ownership (according to the master list). The other three are nonfiction.

**Comment by rebeccarubenstein** [comment]
I'm on it.

**Comment by rebeccarubenstein** [comment]
@nevanscott @ftpavlik This should all be set. I'm wondering: rather than straight-up nonfiction, do we want to label Susan's piece Oral History?

**Comment by nevanscott** [comment]
I kinda like Oral History, personally.

**Comment by nevanscott** [comment]
I'll leave it up to you guys what you think...

**Comment by rebeccarubenstein** [comment]
I changed it to Oral History, but @ftpavlik, feel free to weigh in.

**Comment by nevanscott** [comment]
I'm considering this closed for now...

**Comment by ftpavlik** [comment]
I'll chime in late to say I'm cool with Oral History. Sorry I was offline
for a bit.
