### ISSUE TITLE
Bios

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#70]
Feel free to pull in bios and I will make necessary formatting edits on them once they're added to the drafts. Bios are [here](https://docs.google.com/document/d/1FbEJgAMRJx-dWdPt3riyReVcoks4lseI3ewTSVWJCfw/edit?usp=sharing).

**Comment by nevanscott** [comment]
These should be in now, and are updating to the preview site as I write this, if you want to double-check any, see the commit above for where/how I added them in.

**Comment by rebeccarubenstein** [comment]
These look good. Thanks for taking care of the formatting.
