### ISSUE TITLE
Order for pieces?

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#71]
Could you choose an order for the pieces?

This is where the order can be changed:

https://github.com/midnightbreakfast/web/blob/issues/1/_src/_data/issues.yml#L4-L9

**Comment by rebeccarubenstein** [comment]
Updated the order. Can you push the changes on the preview site and we can see what it looks like?

**Comment by nevanscott** [comment]
Updated with the new order. See also my note, I think you accidentally deleted an extra line.

**Comment by rebeccarubenstein** [comment]
Updated again. How do you feel about having Wendy's photo beneath Erika's piece's illo? Is there too much of an echo in style? I kind of like how the color of Gabrielle's illo bounces off Migueltzinta's better.

**Comment by nevanscott** [comment]
Check it again, because there are different thumbnails now...

**Comment by rebeccarubenstein** [comment]
Switched it around again -- can you push the current changes? (Sorry, I'm just trying to get it to be as visually striking as possible.)

**Comment by nevanscott** [comment]
Keep in mind that it changes depending on what size screen you have: there are actually two layouts…  

Updating now...

**Comment by rebeccarubenstein** [comment]
I'm an idiot and added an extra D in "Some Pride," so it'll need to be pushed again to properly update. Sorry...

**Comment by nevanscott** [comment]
We’ll have to figure out how to do a better job of being careful while everyone’s making changes in the future. Unfortunately the website doesn’t make it super easy to do on its own...

**Comment by rebeccarubenstein** [comment]
THIS IS THE ORDER! I'm into it. (If you're into it.)

Oh man, can I tell you how good the homepage looks? It looks soooo good.

**Comment by nevanscott** [comment]
I still need to do some work on it... But thank you :)

**Comment by rebeccarubenstein** [comment]
I'ma gonna close this, if that's cool?
