### ISSUE TITLE
Add gallery to Orange Valley Lodge piece

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#72]

**Comment by nevanscott** [comment]
@rebeccarubenstein 

This would be huge if you could help a little with this in terms of what might make sense with the content.

I've got 9 photos to work with in total, all of which have captions. I don't know whether to pick a few to place going down the page, or maybe just have one + have a gallery popup kinda thing. Do you have any thoughts on what will work best with the piece?

**Comment by rebeccarubenstein** [comment]
@nevanscott Where are the photos?

**Comment by nevanscott** [comment]
They're in a couple of emails from Doug right now. Sorry I'm headed to dinner at the moment...

**Comment by rebeccarubenstein** [comment]
@nevanscott  The sooner I look at this stuff, the sooner we get it done. Please forward me the emails.

**Comment by rebeccarubenstein** [comment]
My thoughts: if it's not too much work for you to create some kind of gallery, that might be best in this instance. But if it is, then I'd recommend going with a large photo before the text, then a photo at each section break, then a photo beneath the text, right before Susan's bio. If we go with the latter, the order should probably be:
- Photo 02
- Photo 03
- Photo 04
- Photo 05
- Photo 06

If we go with the gallery, the order should be:
- Photo 02
- Photo 04
- Photo 03
- Photo 01
- Photo 07
- Photo 06
- Photo 08
- Photo 05

**Comment by nevanscott** [comment]
I went with the first option for the sake of time... I actually think it may work better. Uploading soon.

**Comment by nevanscott** [comment]
This will be up in a minute, at which point, could you double-check the captions and that everything makes sense to you?

**Comment by rebeccarubenstein** [comment]
I know you probably want to go to sleep, but do you think this would work better if the photos were spanning the length of the text and dividing the breaks, rather than alongside? Since this is a photo/text piece, it kind of looks weird...like the photos are just an accessory.

**Comment by nevanscott** [comment]
Personally, I prefer it this way, since it keeps all the photos so that you can see them within 1 screen without having to scroll through them. The layout is like what you say on smaller screens though.

**Comment by rebeccarubenstein** [comment]
Do we have an ability to enlarge the photos for desktop then?

Just checked it on my phone and the last photo is a little small. 

My main concern with all this is the details that get lost when the photos are smaller like this.

**Comment by rebeccarubenstein** [comment]
By which I mean, if we have the ability where someone can click on them and then they're either taken to a large version of the image, or the image pops out in a larger version.

**Comment by nevanscott** [comment]
OK: How critical is this?

**Comment by nevanscott** [comment]
I mean, I want things to be good, but I'm dying a bit...

**Comment by rebeccarubenstein** [comment]
It's critical. It's a text/photo piece. This is how it was always packaged — the photos are supposed to be as important as the text.

**Comment by rebeccarubenstein** [comment]
It took a lot for me to even get this piece, so please work with me here.

**Comment by nevanscott** [comment]
I'm working on it... Should the byline be different to include both in that case?

**Comment by rebeccarubenstein** [comment]
I think the byline can remain as is. Let's just try and feature the photos more prominently, or make it so they expand if you click on them. Remember what you did for <cite>The Aqiqah</cite>? It would be kind of amazing if you did that here.

**Comment by nevanscott** [comment]
OK, I'm pretty happy with this if you are:

http://preview.midnightbreakfast.com/orange-valley-lodge-13/

**Comment by rebeccarubenstein** [comment]
I think you should hit publish. It's 12:15 here, so no one's gonna know and then you don't have to worry about doing it in the morning.

**Comment by nevanscott** [comment]
Is that you signing off on this?

**Comment by rebeccarubenstein** [comment]
Yes. And the issue. Let's do this.
