### ISSUE TITLE
Update Contributors page to include Issue 1

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#73]

**Comment by nevanscott** [comment]
@rebeccarubenstein When the changes finally make it up, will you take a look? You'll know it's up when it says "Issue 1" near the top to the list... (Hint: not yet.)

**Comment by rebeccarubenstein** [comment]
@nevanscott  I see a few things that need edits. Link me to the place where I can do that, so you can take care of other stuff?

**Comment by nevanscott** [comment]
OK, should be up as intended now. Please take a look. If you want to change the intro copy, it's way down at the bottom of this:

https://github.com/midnightbreakfast/web/blob/issues/1/_src/pages/contributors.md

(Insane, I know, it'll get better in the future...)

**Comment by rebeccarubenstein** [comment]
I jumped the gun this time. :)

**Comment by rebeccarubenstein** [comment]
For some reason, it says "Orange Valley Lodge" on the page, but "Orange Valley Lodge #13" in the editor. Not sure what's happening? I've refreshed a few times and it's still there.

**Comment by nevanscott** [comment]
Put quotes around the title, it's treating everything after a "#" as a comment

**Comment by nevanscott** [comment]
so like:

```
title: "blah blah #blah"
```

**Comment by rebeccarubenstein** [comment]
Made the changes, just needs a push to see if it went through.

**Comment by nevanscott** [comment]
OK, take a look, should be good to go.

**Comment by rebeccarubenstein** [comment]
Yup!
