### ISSUE TITLE
Em-dashes

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#74]
Just an FYI: to keep things consistent with Issue 0 style, I fixed the em-dashes in all the pieces so they're separated from text, rather than attached. You can see an example in the first sentence here:

http://preview.midnightbreakfast.com/orange-valley-lodge-13/

**Comment by nevanscott** [comment]
Another also: could you attach these kinds of things to the Issue 1 milestone? I just did it for this one.

**Comment by rebeccarubenstein** [comment]
No problem. If you've seen this and you're cool with it, can you close it out?

**Comment by nevanscott** [comment]
Yup, sounds fine to me. We can have a style conversation later on...
