### ISSUE TITLE
Copy Checked

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#76]
All copy has been checked on my and Taylor's end. Let us know when you're finalizing the drafts and we'll do final proofreads to make sure we haven't missed anything.

**Comment by nevanscott** [comment]
@rebeccarubenstein @ftpavlik 

Closing this out, seems like this has been an overall very smooth process... Hope you guys are in agreement. Still really appreciate you both doing production with me. Much less lonely than it could be.
