### ISSUE TITLE
In Conversation with Wendy C. Ortiz: Hyperlink

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#79]
Some changes need to be pushed, so I'm not sure if this is why the hyperlink isn't working, but the first instance of <cite>Excavation</cite> is supposed to bring readers to the Future Tense site. Currently it doesn't. Maybe something with the way I set up the tags?

**Comment by nevanscott** [comment]
Is it working now?

**Comment by rebeccarubenstein** [comment]
Doesn't seem to be...

**Comment by nevanscott** [comment]
Are you sure? It looks like there are links now to me. Did you try refreshing?

**Comment by rebeccarubenstein** [comment]
I don't know what's up. I tried to get rid of the cache, but it's still taking me to a 404 page (on both Safari AND Chrome). Could you test the link?

**Comment by nevanscott** [comment]
OK, I thought you were talking about a different issue, I hadn't tried clicking the link. See above for how I fixed it... I think you just made a simple mistake when you switched to markdown.

**Comment by rebeccarubenstein** [comment]
Oh damn, yeah, THAT was dumb of me. All this toggling between markdown and HTML. My brain hurts.

Thanks. All good now!

**Comment by nevanscott** [comment]
Is it working now? I think it is...

**Comment by nevanscott** [comment]
Oh cool, jumped the gun. :)
