### ISSUE TITLE
Confirm formatting on Rooms

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#80]
@ftpavlik 

I made some additional changes toward the end in terms of formatting. The standard on the site (like for interviews) is to do dialogue with bolded names, so I applied that to the dialogue at the end.

I also attempted to reinstate a space that I thought was there before but had gone missing. Can you check it out and let me know what you think?

Thanks,
Nevan

**Comment by ftpavlik** [comment]
Bolding is showing up fine. Where was the space added? I don't see any missing spaces so far.

**Comment by nevanscott** [comment]
Before "A few hours before arriving in Stockton we texted:" right at the end.

P.S. If you want me to look at an issue again, would you mind reassigning it to me?

**Comment by ftpavlik** [comment]
Copy is good here. Thanks! All it needs is the illustrator credit.
