### ISSUE TITLE
Illustrator Copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#81]
I'm sure you're on it, but Taylor wanted to make sure all illustrators/photographers are cited at the bottom of pieces. Let me know if you want me to fill this info in.

**Comment by nevanscott** [comment]
Would you mind getting it started, so I can work on the gallery thingy first?

**Comment by rebeccarubenstein** [comment]
There's no Illustrator field for me to add that info. Is there a way for you to do this for all the pieces? It only seems to exist with Erika's piece.

**Comment by nevanscott** [comment]
OK, these should be added in, along with the place for a URL.

Thank you!

**Comment by rebeccarubenstein** [comment]
These should all be in there. Please double-check all the info is correct before closing the ticket.

**Comment by nevanscott** [comment]
All looks good to me!
