### ISSUE TITLE
Scumbag copy checked

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#84]
Not sure if this is worth creating an issue, but I proofed Scumbag, made a few edits here, and it should be good to go!

**Comment by nevanscott** [comment]
Can you double-check the preview site to make sure? It should be uploaded at this point...

(And, yes, this is what they're for pretty much. Next time, would you mind adding the "Issue 1" milestone? Helps me keep these organized.)

**Comment by nevanscott** [comment]
If it's good to go on Preview, you can close this out.

**Comment by ftpavlik** [comment]
All good!
