### ISSUE TITLE
My Bio

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#85]
I need my bio changed. Let me know if I can make this change myself/where to make it. Otherwise, please amend the following sentence:

"In addition to Midnight Breakfast, she is also the interviews editor for The Rumpus and a former contributing editor for the short-lived but wonderful STET."

It should say:

"In addition to <cite>Midnight Breakfast</cite>, she is a freelance writer and editor, the former interviews editor of <cite>[The Rumpus](http://therumpus.net)</cite>, and a former contributing editor for the short-lived but wonderful <cite>[STET](http://editorially.com/blog)</cite>."

**Comment by nevanscott** [comment]
This can be changed here:

https://github.com/midnightbreakfast/web/blob/issues/1/_src/pages/about.md

**Comment by rebeccarubenstein** [comment]
Made the change, just needs a push.

**Comment by nevanscott** [comment]
I think this is up...

**Comment by rebeccarubenstein** [comment]
Yep, thanks.
