### ISSUE TITLE
Some Pride of Ownership: Finalized Copy

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#86]
Please push the changes, then confirm. Thanks!

**Comment by nevanscott** [comment]
Give it a minute, and this should be updated.

**Comment by rebeccarubenstein** [comment]
Sorry, can you push it one more time? There was a change that didn't come through (probably my fault).

**Comment by nevanscott** [comment]
I think I pushed it up, but it may be a few minutes until you can see it.

**Comment by nevanscott** [comment]
Definitely up now. Take a look.

**Comment by rebeccarubenstein** [comment]
Just looked. Looks good, thanks!
