### ISSUE TITLE
Letter From the Editor

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#87]
Sorry, was rereading for pull quotes and noticed one more thing... Needs one extra push, please. Thanks!

**Comment by nevanscott** [comment]
Will be up in a few minutes...

**Comment by nevanscott** [comment]
OK, check now...

**Comment by rebeccarubenstein** [comment]
Awesome, thanks. Is this permalink staying the same?

**Comment by nevanscott** [comment]
I'm thinking about that right now. Honestly, I'm not crazy about this one, so I'm probably going to change it...

**Comment by rebeccarubenstein** [comment]
Just let me know, because I have a tweet set to go up at 6:50 am PT with the current link.

**Comment by nevanscott** [comment]
It's definitely moving, I just changed it to `/issue-1-letter/`, if that works for you.

**Comment by nevanscott** [comment]
Will be reflected on the preview site momentarily...

**Comment by rebeccarubenstein** [comment]
K, thanks for the heads up!

**Comment by nevanscott** [comment]
Should be up now.
