### ISSUE TITLE
Copy for Shane Jones excerpt

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#88]
Please also update the URL slug based on the title of the book.

More details here:

https://github.com/midnightbreakfast/web/wiki/Small-Plates

**Comment by rebeccarubenstein** [comment]
I don't actually know where to update the URL file. I keep trying to find it but to no avail. :(

**Comment by rebeccarubenstein** [comment]
Also, the copy is updated but I have a few questions:
1. This is an excerpt, so I don't know how you want to handle the title.
2. Within the excerpt itself, all the "I'm not sick anymore"'s should be in list form (and italicized), but I don't know how to do that in Markdown without created a bulleted or numbered list.
3. Where does the following text go? I looked at Lauren Becker's Small Plates file in GH, but couldn't find where you dropped the text:

Interested in having an excerpt from your upcoming book featured on Small Plates? Please feel free to drop us a line at rebecca@midnightbreakfast.com and let us know!

**Comment by nevanscott** [comment]
Well, what should the title be? I mean, I don't think I understand what you're saying...

**Comment by rebeccarubenstein** [comment]
It's an excerpt from a book, so there's no "title" per se. How you have the layout right now is for the title of a story that's from a collection, but doesn't work with a piece of text that's from a novel. So I don't know where I should be putting the copy. The book is called _Crystal Eaters._ The text is taken from a chapter, but the middle of a chapter, not the entire chapter itself, so it'd be incorrect to title this "Chapter X from _Crystal Eaters_."

**Comment by nevanscott** [comment]
OK, I think I came up with a way to deal with this. I/m uploading to the preview site now, so you'll be able to see what I'm doing...

**Comment by nevanscott** [comment]
http://preview.midnightbreakfast.com

**Comment by rebeccarubenstein** [comment]
Looks really good to me. Two Dollar Radio's website is down, but once it's back up, I'm probably going to switch the link to buy the book to the press's buying page (it's currently an Indiebound link). Just a heads up.
