### ISSUE TITLE
Book cover for Jones excerpt

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#89]
If you could, just send me this through here, and then reassign this issue to me?

**Comment by rebeccarubenstein** [comment]
![crystal eaters by shane jones](https://cloud.githubusercontent.com/assets/4043562/3546421/79193940-0883-11e4-9440-57ff42119805.png)

Does this work?

**Comment by nevanscott** [comment]
Maybe, it's a little on the small side though...

**Comment by rebeccarubenstein** [comment]
I couldn't find anything bigger. I did look.

**Comment by rebeccarubenstein** [comment]
![crystal eaters larger](https://cloud.githubusercontent.com/assets/4043562/3547051/e7e1add8-088f-11e4-8f97-4201e1941501.png)

This is a slightly larger version, but it looks shittier since I grabbed it from a screen cap.

Two Dollar Radio's dude has been completely unresponsive to me, and as I mentioned, I asked him repeatedly for a hi-res image, so I don't really know what to tell you...

**Comment by nevanscott** [comment]
They both look pretty crappy... the colors are quite off on the first, now that I see the second. Should we delay until we get a better one? I mean, I get what you're saying, but don't we need to get this sorted out first?

**Comment by rebeccarubenstein** [comment]
The second one is actually closest to the book's cover. The image is actually really grainy and off-colored. 

The problem with delaying is problematic for several reasons: we're not running this next week (submissions open, so I'd rather not have a Small Plates run); I already told the Two Dollar Radio publisher we'd run it this week; and the Two Dollar Radio publisher has consistently ignored my request for a hi-res image so I have no idea if waiting will even yield said image. I really, really get where you're coming from, and I know it's probably making you want to vomit using a lower-quality image, but maybe we can use it as a placeholder and replace it once we finally get a hi-res image? (IF we get a hi-res image?)

**Comment by nevanscott** [comment]
I replaced it with the one with better colors. It'll have to do.

**Comment by rebeccarubenstein** [comment]
As a layperson, this looks totally fine to me.

**Comment by rebeccarubenstein** [comment]
Reopening this because Two Dollar's publisher sent me a hi-res j-peg, in case you wanted to replace the current image.

![crystal eaters_shane jones_cov](https://cloud.githubusercontent.com/assets/4043562/3560398/b3252b20-096a-11e4-9897-ad867d58180e.jpg)

**Comment by nevanscott** [comment]
Thanks, I put it in.
