### ISSUE TITLE
Finalize Submissions page copy

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#90]
@ftpavlik Let me know when this is wrapping up, and I'll help make sure we find a home for it on the site.

**Comment by nevanscott** [comment]
Hey Taylor, just wanted to make sure you had gotten this.

Thanks,
Nevan

**Comment by ftpavlik** [comment]
Hey Nevan,

The submissions copy is ready. Do I need to upload it somewhere?

Thanks,
Taylor

**Comment by nevanscott** [comment]
I'm uploading it now, should be able to update you in a few...

**Comment by nevanscott** [comment]
See here: http://preview.midnightbreakfast.com/submissions/ for a preview.

Make changes to these two, as needed:

https://github.com/midnightbreakfast/web/blob/submissions/_src/pages/about.md

https://github.com/midnightbreakfast/web/blob/submissions/_src/pages/submissions.md

NOTE: These are both in the Submissions branch.

Thanks!
Nevan

P.S. — I am still thinking about the navigation to this page, I'm worrying about that in a separate Issue #92

**Comment by ftpavlik** [comment]
Hey Nevan,

The submissions copy looks good. I don't want to make any changes. I added copy to the about page leading people to submissions.

Thanks!
