### ISSUE TITLE
Figure out where/how to link to Submissions page

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#92]
If there's room in the header, that may make the most sense for now. Eventually, we should probably consider growing out the "About" page into more of a section, including for Submissions...

**Comment by ftpavlik** [comment]
The header is always the first place I look for submissions, but I think it could work in the footer too. I think we need a submissions link somewhere on the front page, since many people will be more concerned with finding that link than the about page.

**Comment by nevanscott** [comment]
@ftpavlik @rebeccarubenstein 

I altered the nav like so:

http://preview.midnightbreakfast.com

As you can see, I dropped the "Thanks" link. But since it's mentioned on the Submissions page, I added a link to the Thanks page:

https://www.dropbox.com/s/kx5rj2ue6gbiuua/Screenshot%202014-07-19%2019.07.29.png

If you guys are okay with the change, let me know, and I'll close this out.

Thanks,
Nevan

**Comment by ftpavlik** [comment]
Can we add the Thanks link to the bottom of the page? I think it's important to have it on the front page.  If you want a line of copy, how about: "Midnight Breakfast is funded thanks to the donations of [link]many generous readers[/link]." Rebecca, how do you feel about copy to that effect?

**Comment by rebeccarubenstein** [comment]
I was going to say the exact same thing, but you beat me to it, Taylor.

Nevan, can you add that copy?

**Comment by nevanscott** [comment]
Check it:

http://preview.midnightbreakfast.com

@rebeccarubenstein If you approve, please close this issue out.

**Comment by rebeccarubenstein** [comment]
I approve.
