### ISSUE TITLE
Shane Jones excerpt [Editor's Note]

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#93]
How do you feel about the placement of the asterisk text? Should it go after my sign-off?

**Comment by nevanscott** [comment]
I like it better after.

But to be honest, I don't really have any support for footnotes right now and don't have time to implement them properly. Maybe it would be better to make it a "P.S." for now?

You can see it on the preview site.

**Comment by rebeccarubenstein** [comment]
Hmm...should we just cut it?

**Comment by nevanscott** [comment]
Yeah, I think that would probably be best in this case.

**Comment by rebeccarubenstein** [comment]
Okay, feel free to cut it and please take out the asterisk in the first paragraph.

**Comment by nevanscott** [comment]
Am doing so.

Next time, can you also add new ones of these to the appropriate milestone?

**Comment by rebeccarubenstein** [comment]
Yeah. Sorry. I'm still getting used to this milestone thing...

**Comment by nevanscott** [comment]
No worries.
