### ISSUE TITLE
Shane Jones excerpt [Copy re: Copyright]

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#94]
Does this read okay to you? Particularly:

"This excerpt can be found in Crystal Eaters by Shane Jones © 2014 by Two Dollar Radio."

I pretty much made this copy up, since my request for specific copyright language was also ignored. (Basically the dude just said, Yay! Excerpt! Here you go!)

**Comment by nevanscott** [comment]
I don't really know... it's a little weird though to my ear. Maybe look at an anthology and see how they tend to do it?

**Comment by nevanscott** [comment]
I'd also prefer to use the word "copyright" as opposed to the symbol...

**Comment by rebeccarubenstein** [comment]
We can use the word copyright. I don't think I actually have any anthologies on hand...and I'm not home right now...

Should it maybe be:

"This text is excerpted from _Crystal Eaters_ by Shane Jones, copyright 2014 by Two Dollar Radio."

Or perhaps:

"This text appears in _Crystal Eaters_ by Shane Jones, copyright 2014 by Two Dollar Radio."

**Comment by nevanscott** [comment]
Whole thing:

This text is excerpted from _Crystal Eaters_ by Shane Jones, copyright 2014 by Two Dollar Radio, used with permission from Two Dollar Radio.

?

**Comment by rebeccarubenstein** [comment]
That works for me. I mean, if they didn't specify the language, that's on them. And if they want us to change it after-the-fact, we can.

Should I make the change, or do you want to handle it since you'll be pushing it as well?

**Comment by nevanscott** [comment]
I'll do it.

**Comment by rebeccarubenstein** [comment]
Okay, just close the ticket whenever you've made the change.
