### ISSUE TITLE
Launch Shane Jones excerpt

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#95]
When should it go up? I'm assuming it's ready at this point?

**Comment by rebeccarubenstein** [comment]
It's ready. Would you mind launching it tomorrow morning when you wake up and send me and Taylor an email with the hyperlink? (So Taylor can do his Facebook thing, but more importantly, so he can be in the know about when it goes up.)

**Comment by nevanscott** [comment]
@rebeccarubenstein @ftpavlik Just adding you both so I can update once this is up. Here it is on the preview site for now:

http://preview.midnightbreakfast.com/jones-crystal-eaters/

Once launched it should be here:

http://midnightbreakfast.com/jones-crystal-eaters/

**Comment by rebeccarubenstein** [comment]
Thanks, Nevan!

**Comment by nevanscott** [comment]
Hey guys,

It should be up now!

Nevan
