### ISSUE TITLE
Launch Submissions page

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#99]
Right now the plan is to launch on Monday morning.

@rebeccarubenstein @ftpavlik

**Comment by rebeccarubenstein** [comment]
Sounds good. What will be the permalink (so I can pass it on to Ashley)?

**Comment by nevanscott** [comment]
It’ll be at /submissions/, just like on the preview site, unless you want to make a change to the URL before we go live.  

N

**Comment by rebeccarubenstein** [comment]
@nevanscott I need to go in and add a sentence and italicize something. Can you give me the link to the post (branch? what's its proper name?) so I can edit?

**Comment by nevanscott** [comment]
Here's the submissions page:

https://github.com/midnightbreakfast/web/blob/submissions/_src/pages/submissions.md

**Comment by rebeccarubenstein** [comment]
Changes made. Please push them, then this page will be ready for launch.
